### ISSUE TITLE
import file js

### ISSUE THREAD

**Issue by nurdin173** [christbiz86/project-attendees#2]
Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

Tombol menu yang manggil file js tidak jalan

**Comment by christbiz86** [comment]
coba di-replace dgn :
import { createBrowserHistory } from 'history'
@nurdin173

**Comment by nurdin173** [comment]
![image](https://user-images.githubusercontent.com/53600365/62531846-6fe90900-b86d-11e9-9b07-452316ef0604.png)
